### PR TITLE
Fix color space in decompression

### PR DESCRIPTION
**Pull request by vadymmarkov**

### CODE REVIEW

**Comment by vadymmarkov** [comment]
giphy

**Comment by RamonGilabert** [comment]
screen shot 2016-09-07 at 5 08 53 pm

The linking of this gif is being a total fail dude. I'm just going to merge. Let's see if this works.

**Comment by RamonGilabert** [comment]
For the record: @hyperoslo/ios.

**Comment by onmyway133** [comment]
😁

**Pull request merged**
