### PR TITLE
Add Option. Use .DelayPlaceholder to delay the setting of the placeholder

### PR DESCRIPTION
**Pull request by onmyway133**
Add Option. For now it is just delay the setting of the placeholder.

There are cases like the profile page and user changes the profile picture
- If this is the first time user changes the picture, it should display the placeholder -> actual image
- If this is the next time user changes the picture, it should only display the placeholder if the image fetching fails

### CODE REVIEW

**Comment by onmyway133** [comment]
And we need unit test as well 😁

**Comment by aashishdhawan** [comment]
> If this is the first time user changes the picture, it should display the placeholder -> actual image
> If this is the next time user changes the picture, it should only display the placeholder if the image fetching fails

@onmyway133 I think we should not handle this in `Imaginary` itself but the place where we are using it. We should try to make public API [as simple as it can be but not simpler](http://quoteinvestigator.com/2011/05/13/einstein-simple/).

**Comment by vadymmarkov** [comment]
@onmyway133 Should we resolve conflicts and merge or close this one? 😄

**Comment by onmyway133** [comment]
@aashishdhawan @vadymmarkov I agree that this is a bit customization and not for generic usage. But this is something that can only be done inside Imaginary. So I'm not sure if we should continue with this approach or not. Basically, there are some more options to come, and more logic checking in the code if we go with this 😈

**Comment by onmyway133** [comment]
This PR is too old, close for now

**Pull request closed without merging**
